### ISSUE TITLE
SBOl 

### ISSUE THREAD

**Issue by CoolEJ** [SynBioDex/SBOLCanvas#285]
![SBOLCanvasUploadIssue](https://github.com/SynBioDex/SBOLCanvas/assets/28577691/f19f04d2-26e1-4afa-ac50-af578796c876)

I am still having issues uploading in SBOL Canvas. Please see attached image.

**Comment by cjmyers** [comment]
Could you also post the image of your circuit?  Also, if you cannot get it to submit to SynBioHub, you can just turn in the image of your circuit.

**Comment by CoolEJ** [comment]
Here it is.
![FA (2)](https://github.com/SynBioDex/SBOLCanvas/assets/28577691/294c1c03-183b-4dc4-9ec1-606019fd7713)

**Comment by cjmyers** [comment]
The diagram is nice and detailed.  I suggest submitting this for your assignment.  

There are though some things in your diagram that may be causing the issue.  You are using labels instead of small molecule and protein icons for these objects.  Also, for repression by IPTG, aTc, etc, these are better expressed in our tool using complex formation (i.e., the precise mechanism).

**Comment by Drock54651** [comment]
Fixed by PR #289
